java:
  java_cmd: "java"
  mvn_cmd: "mvn"
resources:
  max-threads: 12
  memory: "50G"
scenarios:
  baseline:
    path: "/path/to/baseline"
    prefix: "ile_de_france_"
  gpe:
    path: "/path/to/gpe"
    prefix: "ile_de_france"
output_path: "/path/to/output"