import os
import glob
import sys
import importlib.util


spec = importlib.util.spec_from_file_location("lib", "lib/__init__.py")
module_obj = importlib.util.module_from_spec(spec)
sys.modules["lib"] = module_obj
spec.loader.exec_module(module_obj)

from lib import PipelineConfig
from lib import to_absolute
from lib import memory_string_to_mb

config_object = PipelineConfig(config, workflow.basedir, workflow.cores)

def repo_url_to_id(repo_url):
    # SSH link example "git@github.com:eqasim-org/ile-de-france.git"
    # HTTPS link example https://github.com/eqasim-org/ile-de-france.git
    assert isinstance(repo_url, str)
    if not repo_url.startswith("git@github.com") and not repo_url.startswith("https://github.com"):
        raise Exception("Invalid repo_url")
    components = repo_url.split("/")
    repo_owner, repo_name = components[-2], components[-1]
    repo_name = repo_name.replace(".git", "")
    repo_owner = repo_owner.split(":")[-1]
    return "%s/%s" % (repo_owner, repo_name)

# General resources
temp_path = config_object.temp_path
java_cmd = config_object.java.java_cmd
mvn_cmd = config_object.java.mvn_cmd



# Basic input simulation files related file paths

original_simulation_files_paths = [to_absolute(os.path.join(config_object.general_inputs_config.input_path, f), workflow.basedir) for f in os.listdir(config_object.general_inputs_config.input_path)]

# The locations of the files that input files after they will be copied
simulation_files_paths = [os.path.join(config_object.global_simulation_inputs_location, f) for f in os.listdir(config_object.general_inputs_config.input_path)]
# The name of the base config file (in the original location as well as in the copied one)
input_config_file_name = "%sconfig.xml" % config_object.general_inputs_config.input_prefix

rule copy_sim_files:
    input:
        original_simulation_files_paths
    output:
        simulation_files_paths
    threads: 1
    resources:
        mem_mb=2048
    shell:
        """
        cp {config_object.general_inputs_config.input_path}/* {config_object.global_simulation_inputs_location}
        """

# Maven and Java related variables
mvn_project_base_path = to_absolute("../../../../", workflow.basedir)
pom_path = os.path.join(mvn_project_base_path, "pom.xml")
java_sources_base_path = to_absolute("../java", workflow.basedir)
java_sources_paths = [to_absolute(f, workflow.basedir) for f in glob.iglob(java_sources_base_path + "**/**", recursive=True) if os.path.isfile(f)]

jar_path = os.path.join(mvn_project_base_path, "dourdan_feeder_drt_2024", "target", "dourdan_feeder_drt_2024-1.0-SNAPSHOT.jar")

# This rule is meant to compile the ile_de_france package in eqasim-java into a Jar with all the dependencies
rule compile:
    input:
        java_sources_paths,
        pom_path
    output:
        jar_path
    threads: 4
    resources:
        mem_mb=2048
    shell:
        '{mvn_cmd} package -Pstandalone --also-make --file "{pom_path}" -Dmaven.repo.local="{config_object.java.mvn_local_repo}"'

# This rule is to make sure that we properly configure the global simulation before running it
rule baseline_config:
    input:
        jar_path,
        config_object.global_simulation_input_file_path("config.xml")
    output:
        config_object.global_baseline_config_path
    threads: 1
    resources:
        mem_mb=2048
    shell:
        """
        {java_cmd} -cp "{input[0]}" org.eqasim.core.simulation.mode_choice.epsilon.AdaptConfigForEpsilon \
        --input-config-path="{input[1]}" --output-config-path="{output[0]}"
        {java_cmd} -cp "{input[0]}" org.eqasim.core.simulation.vdf.utils.AdaptConfigForVDF \
        --input-config-path="{output[0]}" \
        --output-config-path="{output[0]}" --engine=true \
        --config:eqasim:vdf_engine.generateNetworkEvents=true \
        --config:eqasim:vdf.writeTravelTimesInterval=1 --config:controller.lastIteration=0 \
        --config:swissRailRaptor.transferCalculation=Adaptive \
        --config:eqasim:vdf.handler Horizon
        """

baseline_trips_path = config_object.global_simulation_output_file_path("eqasim_trips.csv")
baseline_plans_path = config_object.global_simulation_output_file_path("output_plans.xml.gz")
baseline_events_path = config_object.global_simulation_output_file_path("output_events.xml.gz")
baseline_travel_times_path = config_object.global_simulation_output_file_path("vdf_travel_times.bin")


rule global_simulation_baseline:
    input:
        config_object.global_baseline_config_path
    output:
        baseline_trips_path,
        baseline_plans_path,
        baseline_events_path,
        baseline_travel_times_path
    threads: config_object.global_simulation_resources.threads
    resources:
        mem_mb=memory_string_to_mb(config_object.global_simulation_resources.memory),
        runtime=config_object.global_simulation_resources.runtime
    shell:
        '''
        {java_cmd} -cp "{jar_path}" -Xmx{config_object.global_simulation_resources.memory} -XX:MaxRAMPercentage=100.0 \
        org.eqasim.ile_de_france.RunSimulation --config-path="{input[0]}" \
        --config:controller.outputDirectory={config_object.global_simulation_outputs_location} \
        --config:global.numberOfThreads={threads}
        '''


rule area_buffer:
    input:
        lambda wildcards: config_object.get_area_by_prefix(wildcards.area_prefix).path
    output:
        "%s/misc/{area_prefix}area_buffer.gpkg" % config_object.output_path
    params:
        buffer_length=lambda wildcards: config_object.get_area_by_prefix(wildcards.area_prefix).buffer_length,
        runtime=5
    run:
        import geopandas as gpd
        gdf = gpd.read_file(input[0])
        gdf = gpd.GeoDataFrame(geometry=gdf.buffer(params.buffer_length), crs=gdf.crs)
        gdf.to_file(output[0])

rule cutter:
    input:
        jar_path,
        config_object.global_baseline_config_path,
        baseline_plans_path,
        baseline_events_path,
        baseline_travel_times_path,
        "%s/misc/{area_prefix}area_buffer.gpkg" % config_object.output_path
    output:
        "%s/scenarios/{area_prefix}scenario/{area_prefix}config.xml" % config_object.output_path,
        "%s/scenarios/{area_prefix}scenario/{area_prefix}network.xml.gz" % config_object.output_path,
        "%s/scenarios/{area_prefix}scenario/{area_prefix}transit_schedule.xml.gz" % config_object.output_path
    threads: config_object.cutter_resources.threads
    resources:
        mem_mb=memory_string_to_mb(config_object.cutter_resources.memory),
        runtime=config_object.cutter_resources.runtime
    params:
        output_dir=lambda wildcards: config_object.area_simulation_inputs_location(config_object.get_area_by_prefix(wildcards.area_prefix).id)
    shell:
        """
        {java_cmd} -cp "{input[0]}" -Xmx{config_object.cutter_resources.memory} -XX:MaxRAMPercentage=100.0 org.eqasim.core.scenario.cutter.RunScenarioCutterV2 \
        --config-path={input[1]} --plans-path={input[2]} \
         --events-path={input[3]} \
         --vdf-travel-times-path={input[4]} \
         --extent-path={input[5]} \
         --prefix={wildcards.area_prefix} \
         --flag-area-link-modes=true  \
         --threads={config_object.cutter_resources.threads} \
         --output-path={params.output_dir} \
         --config:eqasim:vdf.writeInterval 0 \
         --config:eqasim:vdf.writeFlowInterval 0 \
         --config:eqasim:vdf.writeTravelTimesInterval 0 \
        """

wildcard_constraints:
    area_prefix="[^g].+"

rule area_simulation_baseline:
    input:
        jar_path,
        lambda wildcards: config_object.area_baseline_config_path(config_object.get_area_by_prefix(wildcards.area_prefix).id)
    output:
        ["%s/simulations/{area_prefix}baseline/%s" % (config_object.output_path, f) for f in PipelineConfig.RELEVANT_SIMULATION_OUTPUTS]
    threads: config_object.area_baseline_simulation_resources.threads
    resources:
        mem_mb=memory_string_to_mb(config_object.area_baseline_simulation_resources.memory) + 10240,
        runtime=config_object.area_baseline_simulation_resources.runtime
    params:
        output_dir=lambda wildcards: "%s/simulations/%sbaseline" % (config_object.output_path, wildcards.area_prefix)
    shell:
        '''
        {java_cmd} -Xmx{config_object.area_baseline_simulation_resources.memory} -XX:MaxRAMPercentage=100.0 -cp {jar_path} org.eqasim.ile_de_france.RunSimulation \
        --config-path {input[1]} \
        --config:global.numberOfThreads {config_object.area_baseline_simulation_resources.threads} \
        --config:controller.outputDirectory {params.output_dir} \
        --config:controller.lastIteration 100
        '''

rule drt_vehicles:
    input:
        jar_path,
        "%s/scenarios/{area_prefix}scenario/{area_prefix}network.xml.gz" % config_object.output_path
    output:
        "%s/scenarios/{area_prefix}scenario/{area_prefix}drt_vehicles/{fleetSize}_{vehicleCapacity}_{seed}.xml" % config_object.output_path
    resources:
        mem_mb=4096,
        runtime=20
    threads: 1
    shell:
        '''
        {java_cmd} -cp {input[0]} org.eqasim.core.simulation.modes.drt.utils.CreateDrtVehicles \
        --network-path={input[1]} \
        --vehicles-number={wildcards.fleetSize} \
        --vehicles-capacity={wildcards.vehicleCapacity} \
        --network-modes=inside_car \
        --output-vehicles-path={output[0]} \
        --random-seed={wildcards.seed} \
        --service-end-time=180000
        '''

rule cost_params:
    params:
        cost_params=lambda wildcards: config_object.get_cost_params(wildcards.deployment_scenario, wildcards.price)
    resources:
        runtime=1
    output:
        "%s/misc/cost_parameters/{deployment_scenario}/{price}.yaml" % config_object.output_path
    run:
        import yaml
        with open(output[0], "w") as f:
            yaml.dump(params.cost_params, f, default_flow_style=False)

rule network_gpkg:
    input:
        jar_path=jar_path,
        network_path="%s/scenarios/{area_prefix}scenario/{area_prefix}network.xml.gz" % config_object.output_path,
        schedule_path="%s/scenarios/{area_prefix}scenario/{area_prefix}transit_schedule.xml.gz" % config_object.output_path
    params:
        crs="EPSG:2154"
    output:
        "%s/misc/{area_prefix}network.gpkg" % config_object.output_path
    threads: 1
    resources:
        mem_mb=2048,
        runtime=30
    shell:
        """
        {java_cmd} -Xmx2G -cp {input.jar_path} org.eqasim.core.tools.ExportTransitLinesToGeopackage \
        --schedule-path {input.schedule_path} --network-path {input.network_path} \
        --crs {params.crs} --output-path={output[0]}
        """

rule modified_transit_schedule_lines:
    input:
        schedule_gpkg="%s/misc/{area_prefix}network.gpkg" % config_object.output_path,
        legs="%s/simulations/{area_prefix}baseline/eqasim_legs.csv" % config_object.output_path,
        pt_legs="%s/simulations/{area_prefix}baseline/eqasim_pt.csv" % config_object.output_path,
        area=lambda wildcards: config_object.get_area_by_prefix(wildcards.area_prefix).path
    params:
        lambda wildcards: config_object.get_modified_transit_schedule_params(wildcards.schedule)
    threads: 1
    resources:
        mem_mb=4096,
        runtime=30
    output:
        "%s/modified_transit_schedules/{schedule}/{area_prefix}lines_to_remove.csv" % config_object.output_path
    notebook:
        "notebooks/get_unused_buses.ipynb"

rule modified_transit_schedule:
    input:
        jar = jar_path,
        lines = "%s/modified_transit_schedules/{schedule}/{area_prefix}lines_to_remove.csv" % config_object.output_path,
        schedule = "%s/scenarios/{area_prefix}scenario/{area_prefix}transit_schedule.xml.gz" % config_object.output_path
    threads: 1
    resources:
        mem_mb=2048,
        runtime=30,
    output:
        "%s/modified_transit_schedules/{schedule}/{area_prefix}transit_schedule.xml.gz" % config_object.output_path
    shell:
        """
        {java_cmd} -Xmx2G -cp {input.jar}  org.eqasim.papers.dourdan_feeder_drt_2024.RemoveTransitLines \
        --schedule-path {input.schedule} --lines-path {input.lines} \
        --output-path {output[0]}
        """

rule modified_transit_schedule_plans:
    input:
        jar = jar_path,
        schedule = "%s/modified_transit_schedules/{schedule}/{area_prefix}transit_schedule.xml.gz" % config_object.output_path,
        config = lambda wildcards: config_object.area_baseline_config_path(config_object.get_area_by_prefix(wildcards.area_prefix).id),
        plans = lambda wildcards: config_object.area_baseline_simulation_output_file_path(config_object.get_area_by_prefix(wildcards.area_prefix).id, "output_plans.xml.gz")
    threads: config_object.area_routing_resources.threads
    resources:
        mem_mb=memory_string_to_mb(config_object.area_routing_resources.memory),
        runtime=config_object.area_routing_resources.runtime
    output:
        "%s/modified_transit_schedules/{schedule}/{area_prefix}plans.xml.gz" % config_object.output_path
    shell:
        """
        {java_cmd} -Xmx{config_object.area_routing_resources.memory} -cp {input.jar} \
        org.eqasim.core.scenario.routing.RunPopulationRouting \
        --config-path {input.config} --config:transit.transitScheduleFile {input.schedule} \
        --config:plans.inputPlansFile {input.plans} \
        --config:swissRailRaptor.transferCalculation Initial \
        --modes pt --threads {threads} --output-path {output[0]}
        """

rule drt_stops:
    input:
        jar_path,
        lambda wildcards: config_object.get_area_by_prefix(wildcards.area_prefix).path,
        "%s/scenarios/{area_prefix}scenario/{area_prefix}transit_schedule.xml.gz" % config_object.output_path,
        "%s/scenarios/{area_prefix}scenario/{area_prefix}network.xml.gz" % config_object.output_path,
    threads: 1
    resources:
        mem_mb=2048,
        runtime=30
    output:
        "%s/scenarios/{area_prefix}scenario/{area_prefix}drt_stops.xml" % config_object.output_path
    shell:
        """
        {java_cmd} -Xmx2G -cp {input[0]} org.eqasim.papers.dourdan_feeder_drt_2024.TransitScheduleToDrtStops \
        --schedule-path {input[2]} --extent-path {input[1]} --network-path {input[3]} \
        --mode inside_car \
        --output-path {output[0]}
        """

rule deployment_scenario_config:
    input:
        lambda wildcards: [jar_path] + config_object.get_deployment_scenario_configure_inputs(config_object.get_area_by_prefix(wildcards.area_prefix).id, wildcards.deployment_scenario)
    output:
        "%s/scenarios/{area_prefix}scenario/{area_prefix}config_{deployment_scenario}.xml" % config_object.output_path
    threads: 1
    resources:
        mem_mb=2048,
        runtime=5
    params:
        args=lambda wildcards: config_object.get_deployment_scenario_configure_args(wildcards.deployment_scenario, config_object.get_area_by_prefix(wildcards.area_prefix).id)
    shell:
        """
        {java_cmd} -Xmx2G -cp {input[0]} org.eqasim.papers.dourdan_feeder_drt_2024.ConfigureDrtServices \
        --input-path {input[1]} --output-path {output[0]} \
        --config:multiModeDrt.drt[mode=drt].operationalScheme serviceAreaBased \
        --config:multiModeDrt.drt[mode=drt].drtServiceAreaShapeFile {input[2]} \
        --config:eqasim.estimator[mode=drt].estimator DrtUtilityEstimator \
        --config:dvrp.networkModes inside_car \
        {params.args}
        """

rule demand_identification_simulation:
    input:
        unpack(lambda wildcards: config_object.get_simulation_inputs(wildcards.area_id, wildcards.hash, demand_identification=True, jar_path=jar_path))
    output:
        ["%s/simulations/demand_identification/{area_id}/{group}/{hash}/%s" % (config_object.output_path, sim_output) for sim_output in PipelineConfig.RELEVANT_SIMULATION_OUTPUTS],
        "%s/simulations/demand_identification/{area_id}/{group}/{hash}/dvrp_travel_times.csv.gz" % config_object.output_path
    threads: config_object.demand_identification_simulation_resources.threads
    resources:
        mem_mb=memory_string_to_mb(config_object.demand_identification_simulation_resources.memory) + 10240,
        runtime=config_object.demand_identification_simulation_resources.runtime
    params:
        output_dir=lambda wildcards: "%s/simulations/demand_identification/%s/%s/%s" % (config_object.output_path, wildcards.area_id, wildcards.group, wildcards.hash),
        args=lambda wildcards: config_object.get_simulation_args(wildcards.hash, demand_identification=True)
    shell:
        """
        {java_cmd} -XX:MaxRAMPercentage=100.0 -Xmx{config_object.area_baseline_simulation_resources.memory} -cp {input.jar_path} \
        org.eqasim.papers.dourdan_feeder_drt_2024.RunSimulation --config-path {input.config} \
        --config:multiModeDrt.drt[mode=drt].vehiclesFile {input.vehicles} \
        --config:plans.inputPlansFile {input.plans} \
        --config:controller.outputDirectory {params.output_dir} \
        --config:eqasim.costParametersPath {input.cost_params} {params.args} \
        --config:transit.transitScheduleFile {input.transit_schedule}
        """


rule fleet_sizing_simulation:
    input:
        unpack(lambda wildcards: config_object.get_simulation_inputs(wildcards.area_id, wildcards.hash, demand_identification=False, fleet_size=wildcards.fleet_size, random_seed=wildcards.seed, jar_path=jar_path))
    output:
        "%s/simulations/fleet_sizing/{area_id}/{group}/{hash}/{fleet_size}/seeds/{seed}.zip" % (config_object.output_path)
    params:
        output_dir = lambda wildcards: "%s/simulations/fleet_sizing/%s/%s/%s/%s/seeds/%s" % (config_object.output_path, wildcards.area_id, wildcards.group, wildcards.hash, wildcards.fleet_size, wildcards.seed),
        args = lambda wildcards: config_object.get_simulation_args(wildcards.hash, demand_identification=False)
    threads: config_object.single_iteration_simulation_resources.threads
    resources:
        mem_mb=memory_string_to_mb(config_object.single_iteration_simulation_resources.memory) + 10240,
        runtime=config_object.single_iteration_simulation_resources.runtime
    shell:
        """
        {java_cmd} -XX:MaxRAMPercentage=100.0 -Xmx{config_object.area_baseline_simulation_resources.memory} -cp {input.jar_path} \
        org.eqasim.papers.dourdan_feeder_drt_2024.RunSimulation --config-path {input.config} \
        --config:multiModeDrt.drt[mode=drt].vehiclesFile {input.vehicles} \
        --config:plans.inputPlansFile {input.plans} \
        --config:controller.outputDirectory {params.output_dir} \
        --config:eqasim.costParametersPath {input.cost_params} {params.args} \
        --config:dvrp.initialTravelTimesFile {input.dvrp_travel_times} \
        --config:transit.transitScheduleFile {input.transit_schedule}
        zip -r -j -m -T {params.output_dir}.zip {params.output_dir}
        """


def get_rejection_rate(sim_path):
    import pandas as pd
    import os
    import zipfile
    if os.path.isfile(sim_path) and sim_path.endswith(".zip"):
        with zipfile.ZipFile(sim_path) as zip:
            with zip.open("drt_customer_stats_drt.csv") as f:
                df = pd.read_csv(f, sep=";")
    else:
        df = pd.read_csv("%s/drt_customer_stats_drt.csv" % sim_path, sep=";")
    requests = df.iloc[-1]["rides"] + df.iloc[-1]["rejections"]
    rejection_rate = df.iloc[-1]["rejections"] / requests
    return rejection_rate

checkpoint fleet_size_evaluation:
    input:
        ["%s/simulations/fleet_sizing/{area_id}/{group}/{hash}/{fleet_size}/seeds/%d.zip" % (config_object.output_path, seed) for seed in config_object.fleet_sizing_config.fleet_seeds]
    output:
        "%s/simulations/fleet_sizing/{area_id}/{group}/{hash}/{fleet_size}/best.zip" % config_object.output_path
    resources:
        mem_mb=2048,
        runtime=60
    threads: 1
    run:
        import shutil
        # We select the seed with minimum rejection rate
        zips = list(input)
        selected_zip = None
        min_rejection_rate = None
        for zip in zips:
            current_rejection_rate = get_rejection_rate(zip)
            if min_rejection_rate is None or current_rejection_rate < min_rejection_rate:
                min_rejection_rate = current_rejection_rate
                selected_zip = zip
        if min_rejection_rate is None:
            raise Exception("No input!")
        shutil.copy(selected_zip, output[0])



def fleet_sizing_input(wildcards):
    left = int(config_object.fleet_sizing_config.fleet_size_precision)
    left_checkpoint = checkpoints.fleet_size_evaluation.get(area_id=wildcards.area_id, group=wildcards.group, hash=wildcards.hash, fleet_size=left)
    left_rejection_rate = get_rejection_rate(left_checkpoint.output[0])

    if left_rejection_rate <= float(config_object.fleet_sizing_config.max_rejection_rate):
        return left_checkpoint.output[0]
    right = left * 10
    while True:
        right_checkpoint = checkpoints.fleet_size_evaluation.get(area_id=wildcards.area_id, group=wildcards.group, hash=wildcards.hash, fleet_size=right)
        right_value = get_rejection_rate(right_checkpoint.output[0])
        if right_value > float(config_object.fleet_sizing_config.max_rejection_rate):
            left = right
            right *= 2
        else:
            break
        if config_object.fleet_sizing_config.max_fleet_size is not None and config_object.fleet_sizing_config.max_fleet_size < right:
            return right_checkpoint.output[0]

    while right - left > int(config_object.fleet_sizing_config.fleet_size_precision):
        middle = int( (right + left) / 2)
        middle_checkpoint = checkpoints.fleet_size_evaluation.get(area_id=wildcards.area_id, group=wildcards.group, hash=wildcards.hash, fleet_size=middle)
        middle_value = get_rejection_rate(middle_checkpoint.output[0])
        if middle_value < float(config_object.fleet_sizing_config.max_rejection_rate):
            right = middle
            right_checkpoint = middle_checkpoint
        else:
            left = middle
    return right_checkpoint.output[0]


rule fleet_sizing:
    input:
        fleet_sizing_input
    threads: 1
    resources:
        mem_mb=2048,
        runtime=60
    params:
        fleet_size=lambda wildcards, input: str(input[0].split("/")[-2])
    output:
        "%s/simulations/evaluation/{area_id}/{group}/{hash}/results.zip" % config_object.output_path
    run:
        import shutil
        import os
        import zipfile
        shutil.copy(input[0], output[0])
        check = int(params.fleet_size)
        with zipfile.ZipFile(output[0], "a") as zip:
            zip.writestr("fleet_size.txt", params.fleet_size)


rule simulation_summary:
    input:
        "%s/simulations/evaluation/{area_id}/{group}/{hash}/results.zip" % config_object.output_path
    output:
        "%s/simulations/evaluation/{area_id}/{group}/{hash}/summary.yaml" % config_object.output_path
    params:
        summary=lambda wildcards: config_object.hash_to_config(wildcards.hash).get_dict()
    threads: 1
    resources:
        mem_mb=1024,
        runtime=5
    run:
        import yaml
        import os
        import zipfile
        with zipfile.ZipFile(input[0]) as zip:
            with zip.open("fleet_size.txt") as f:
                fleet_size = int(f.read())
        params.summary["fleet_size"] = fleet_size
        with open(output[0], "w") as f:
            yaml.dump(params.summary,  f, default_flow_style=False)


rule all:
    default_target: True
    input:
        expand(["%s/simulations/evaluation/{area_id}/%s/%s/{file}" % (config_object.output_path, simulation_config.deployment_scenario.name, simulation_config.hash_code) for simulation_config in config_object.simulation_configs.values()],
            area_id=list(config_object.area_configs.keys()),
            file=["results.zip", "summary.yaml"]),