temp_path: "temp"
output_path: "outputs"
local_maven_repo: ".m2/repository"
java_cmd: "java"
mvn_cmd: "mvn"

simulation_inputs:
  path: "simulation_inputs"
  prefix: "ile_de_france_"

sub_area:
  area_prefix: "drn_"
  area_path: "drn.shp"

global_simulations:
  threads: 10
  memory: "50G"

area_simulations:
  threads: 10
  memory: "5G"

service:
  demand_identification_fleet_size: 40
  fleet_sizing: [10, 20, 30, 50]