java: # Java and Maven command lines
  java_cmd: "java"
  mvn_cmd: "mvn"
  local_maven_repo: ".m2/repository"

resources:
  global_simulations:
    threads: 10
    memory: "50G"
  cutter:
    threads: 14
    memory: "50G"
  area_simulations:
    threads: 12
    memory: "50G"
  area_routing:
    threads: 10
    memory: "50G"

general_inputs:
  input_path: "inputs/simulation_inputs_1pct"
  input_prefix: "ile_de_france_"
  area_prefix: "drn_"
  area_path: "inputs/drn20.gpkg" # The operating area where we want to implement the service
  area_buffer_length: 5000 # We do not cut the scenario strictly on the operating area, we add a buffer to allow vehicles to travel on links that are not necessarily inside the area
  sampling: 0.01


# Modified transit schedules are defined by removing transit lines from the original schedule
# The lines to remove are based on a usage criteria as observed in the baseline simulation (after cutting)
modified_transit_schedules:
  tsb:
    criteria: "passengers/hour"
    transit_modes: ["bus"]
    scope: "all_day"
    threshold: 50
  tsc:
    criteria: "passengers/hour"
    scope: "peak"
    transit_modes: ["bus"]
    threshold: 50

# Service parameters are grouped into demand impacting and non demand impacting
# This distinction is made to run simulations with mode choice only on unique combination of demand impacting parameters
# Then within each combination, the non demand impacting parameters will then be varied (alongside fleet size) in one-iteration simulations
# Most parameters will always be the same for all considered services, but they can also be different (further increasing the set of simulations), one example here is the prebooking
service_parameters:
  demand_impacting:
    operational_scheme: ["stop_based", "door_to_door"]
    price: ["0.3", "0.6", "0.9"]
    detour_factor: ["+50%", "+1200s"] # Must begin with a + and end either with % or s
  non_demand_impacting:
    vehicle_capacity: [4, 8]
    prebooking:
      separate_per_service: true
      values: [0, 600]


# We define services offered by the DRT fleet
# Each service has a type (unimodal or intermodal) and an availability (all_day or off_peak)
# Moreover, intermodal services configure transfer locations by mode and/or facility ids
services:
  all_day_unimodal:
    type: "unimodal"
    availability: "all_day"
  all_day_intermodal:
    type: "intermodal"
    availability: "all_day"
    transfer_locations:
      transit_modes: ["rail"]
  off_peak_unimodal:
    type: "unimodal"
    availability: "off_peak"

# Then we define deployment scenarios that combine one or more service types (within a single simulation).
# Scenarios can have overrides compared to the baseline, for now we only override the transit schedule
deployment_scenarios:
  group1:
    services: ["all_day_unimodal"]
  group2:
    services: ["all_day_intermodal"]
  group3:
    services: ["all_day_unimodal", "all_day_intermodal"]
  group4:
    services: ["off_peak_unimodal", "all_day_intermodal"]
  group5:
    services: ["all_day_unimodal", "all_day_intermodal"]
    simulation_overrides:
      transit_schedule: "tsb"
  group6:
    services: ["all_day_unimodal", "all_day_intermodal"]
    simulation_overrides:
      transit_schedule: "tsc"
  group7:
    services: ["off_peak_unimodal", "all_day_intermodal"]
    simulation_overrides:
      transit_schedule: "tsc"

# Fleet sizing is handled differently because we aim at finding the minimal fleet size that achieves a rejection rate below a thershold
fleet_sizing:
  demand_identification_fleet_size: 10 # This fleet size will be used in the demand identification simulations, must be part of the list below
  fleet_seeds: 10
  max_rejection_rate: "0.05"
  fleet_size_precision: 5

output_path: "output_1pct"
temp_path: "temp_1pct"
random_seed: 1234