import os
import glob
import sys
import importlib.util


spec = importlib.util.spec_from_file_location("lib", "lib/__init__.py")
module_obj = importlib.util.module_from_spec(spec)
sys.modules["lib"] = module_obj
spec.loader.exec_module(module_obj)

from lib import PipelineConfig
from lib import to_absolute
from lib import memory_string_to_mb

config_object = PipelineConfig(config, workflow.basedir, workflow.cores)

def repo_url_to_id(repo_url):
    # SSH link example "git@github.com:eqasim-org/ile-de-france.git"
    # HTTPS link example https://github.com/eqasim-org/ile-de-france.git
    assert isinstance(repo_url, str)
    if not repo_url.startswith("git@github.com") and not repo_url.startswith("https://github.com"):
        raise Exception("Invalid repo_url")
    components = repo_url.split("/")
    repo_owner, repo_name = components[-2], components[-1]
    repo_name = repo_name.replace(".git", "")
    repo_owner = repo_owner.split(":")[-1]
    return "%s/%s" % (repo_owner, repo_name)

# General resources
temp_path = config_object.temp_path
java_cmd = config_object.java.java_cmd
mvn_cmd = config_object.java.mvn_cmd



# Basic input simulation files related file paths

original_simulation_files_paths = [os.path.join(config_object.general_inputs_config.input_path, f) for f in os.listdir(config_object.general_inputs_config.input_path)]

# The locations of the files that input files after they will be copied
simulation_files_paths = [os.path.join(config_object.global_simulation_inputs_location, f) for f in os.listdir(config_object.general_inputs_config.input_path)]
# The name of the base config file (in the original location as well as in the copied one)
input_config_file_name = "%sconfig.xml" % config_object.general_inputs_config.input_prefix

rule copy_sim_files:
    input:
        original_simulation_files_paths
    output:
        simulation_files_paths
    threads: 1
    resources:
        mem_mb=2048
    shell:
        """
        cp {config_object.general_inputs_config.input_path}/* {config_object.global_simulation_inputs_location}
        """

# Maven and Java related variables
mvn_project_base_path = to_absolute("../../../../", workflow.basedir)
pom_path = os.path.join(mvn_project_base_path, "pom.xml")
java_sources_base_path = to_absolute("../java", workflow.basedir)
java_sources_paths = [to_absolute(f, workflow.basedir) for f in glob.iglob(java_sources_base_path + "**/**", recursive=True) if os.path.isfile(f)]

jar_path = os.path.join(mvn_project_base_path, "dourdan_feeder_drt_2024", "target", "dourdan_feeder_drt_2024-1.0-SNAPSHOT.jar")

# This rule is meant to compile the ile_de_france package in eqasim-java into a Jar with all the dependencies
rule compile:
    input:
        java_sources_paths,
        pom_path
    output:
        jar_path
    threads: 4
    resources:
        mem_mb=2048
    shell:
        '{mvn_cmd} package -Pstandalone --also-make --file "{pom_path}" -Dmaven.repo.local="{config_object.java.mvn_local_repo}"'

# This rule is to make sure that we properly configure the global simulation before running it
rule baseline_config:
    input:
        jar_path,
        config_object.global_simulation_input_file_path("config.xml")
    output:
        config_object.global_baseline_config_path
    threads: 1
    resources:
        mem_mb=2048
    shell:
        """
        {java_cmd} -cp "{input[0]}" org.eqasim.core.simulation.mode_choice.epsilon.AdaptConfigForEpsilon \
        --input-config-path="{input[1]}" --output-config-path="{output[0]}"
        {java_cmd} -cp "{input[0]}" org.eqasim.core.simulation.vdf.utils.AdaptConfigForVDF \
        --input-config-path="{output[0]}" \
        --output-config-path="{output[0]}" --engine=true \
        --config:eqasim:vdf_engine.generateNetworkEvents=true \
        --config:eqasim:vdf.writeTravelTimesInterval=1 --config:controller.lastIteration=0 \
        --config:swissRailRaptor.transferCalculation=Adaptive \
        --config:eqasim:vdf.handler Horizon
        """

baseline_trips_path = config_object.global_simulation_output_file_path("eqasim_trips.csv")
baseline_plans_path = config_object.global_simulation_output_file_path("output_plans.xml.gz")
baseline_events_path = config_object.global_simulation_output_file_path("output_events.xml.gz")
baseline_travel_times_path = config_object.global_simulation_output_file_path("vdf_travel_times.bin")


rule global_simulation_baseline:
    input:
        config_object.global_baseline_config_path
    output:
        baseline_trips_path,
        baseline_plans_path,
        baseline_events_path,
        baseline_travel_times_path
    threads: config_object.global_simulation_resources.threads
    resources:
        mem_mb=memory_string_to_mb(config_object.global_simulation_resources.memory)
    shell:
        '''
        {java_cmd} -cp "{jar_path}" -Xmx{config_object.global_simulation_resources.memory} -XX:MaxRAMPercentage=100.0 \
        org.eqasim.ile_de_france.RunSimulation --config-path="{input[0]}" \
        --config:controller.outputDirectory={config_object.global_simulation_outputs_location} \
        --config:global.numberOfThreads={threads}
        '''



cut_config_path = config_object.area_baseline_config_path
cut_network_path = config_object.area_simulation_input_file_path("network.xml.gz")
cut_transit_schedule_path = config_object.area_simulation_input_file_path("transit_schedule.xml.gz")

rule area_buffer:
    input:
        config_object.general_inputs_config.area_path
    output:
        "%s/misc/%sarea_buffer.gpkg" % (config_object.output_path, config_object.general_inputs_config.area_prefix)
    params:
        buffer_length=config_object.general_inputs_config.area_buffer_length
    run:
        import geopandas as gpd
        gdf = gpd.read_file(input[0])
        gdf = gpd.GeoDataFrame(geometry=gdf.buffer(params.buffer_length), crs=gdf.crs)
        gdf.to_file(output[0])

rule cutter:
    input:
        jar_path,
        config_object.global_baseline_config_path,
        baseline_plans_path,
        baseline_events_path,
        baseline_travel_times_path,
        "%s/misc/%sarea_buffer.gpkg" % (config_object.output_path, config_object.general_inputs_config.area_prefix)
    output:
        cut_config_path,
        cut_network_path,
        cut_transit_schedule_path
    threads: config_object.cutter_resources.threads
    resources:
        mem_mb=memory_string_to_mb(config_object.cutter_resources.memory)
    shell:
        """
        {java_cmd} -cp "{input[0]}" -Xmx{config_object.cutter_resources.memory} -XX:MaxRAMPercentage=100.0 org.eqasim.core.scenario.cutter.RunScenarioCutterV2 \
        --config-path={input[1]} --plans-path={input[2]} \
         --events-path={input[3]} \
         --vdf-travel-times-path={input[4]} \
         --extent-path={input[5]} \
         --prefix={config_object.general_inputs_config.area_prefix} \
         --flag-area-link-modes=true  \
         --threads={config_object.cutter_resources.threads} \
         --output-path={config_object.area_simulation_inputs_location} \
         --config:eqasim:vdf.writeInterval 0 \
         --config:eqasim:vdf.writeFlowInterval 0 \
         --config:eqasim:vdf.writeTravelTimesInterval 0 \
        """


rule area_simulation_baseline:
    input:
        jar_path,
        cut_config_path,
    output:
        PipelineConfig.get_relevant_simulation_inputs(config_object.area_baseline_simulation_outputs_location)
    threads: config_object.area_simulation_resources.threads
    resources:
        mem_mb=memory_string_to_mb(config_object.area_simulation_resources.memory) + 10240
    shell:
        '''
        {java_cmd} -Xmx{config_object.area_simulation_resources.memory} -XX:MaxRAMPercentage=100.0 -cp {jar_path} org.eqasim.ile_de_france.RunSimulation \
        --config-path {cut_config_path} \
        --config:global.numberOfThreads {config_object.area_simulation_resources.threads} \
        --config:controller.outputDirectory {config_object.area_baseline_simulation_outputs_location} \
        --config:controller.lastIteration 100
        '''

rule drt_vehicles:
    input:
        jar_path,
        cut_network_path
    output:
        "%s/{fleetSize}_{vehicleCapacity}_{seed}.xml" % config_object.area_vehicles_files_location
    shell:
        '''
        {java_cmd} -cp {input[0]} org.eqasim.core.simulation.modes.drt.utils.CreateDrtVehicles \
        --network-path={input[1]} \
        --vehicles-number={wildcards.fleetSize} \
        --vehicles-capacity={wildcards.vehicleCapacity} \
        --network-modes=inside_car \
        --output-vehicles-path={output[0]} \
        --random-seed={wildcards.seed}
        '''

rule cost_params:
    params:
        cost_params=lambda wildcards: config_object.get_cost_params(wildcards.deployment_scenario, wildcards.price)
    output:
        "%s/cost_parameters/{deployment_scenario}/{price}.yaml" % config_object.area_simulation_inputs_location
    run:
        import yaml
        with open(output[0], "w") as f:
            yaml.dump(params.cost_params, f, default_flow_style=False)


rule network_gpkg:
    input:
        jar_path=jar_path,
        schedule_path=config_object.area_simulation_input_file_path("transit_schedule.xml.gz"),
        network_path=config_object.area_simulation_input_file_path("network.xml.gz")
    params:
        crs="EPSG:2154"
    output:
        "%s/misc/network.gpkg" % config_object.output_path
    threads: 1
    resources:
        mem_mb=2048
    shell:
        """
        {java_cmd} -Xmx2G -cp {input.jar_path} org.eqasim.core.tools.ExportTransitLinesToGeopackage \
        --schedule-path {input.schedule_path} --network-path {input.network_path} \
        --crs {params.crs} --output-path={output[0]}
        """

rule modified_transit_schedule_lines:
    input:
        schedule_gpkg="%s/misc/network.gpkg" % config_object.output_path,
        legs=config_object.area_baseline_simulation_output_file_path("eqasim_legs.csv"),
        pt_legs=config_object.area_baseline_simulation_output_file_path("eqasim_pt.csv"),
        area=config_object.general_inputs_config.area_path
    params:
        lambda wildcards: config_object.get_modified_transit_schedule_params(wildcards.schedule)
    threads: 1
    resources:
        mem_mb=4096
    output:
        "%s/modified_transit_schedules/{schedule}/lines_to_remove.csv" % config_object.output_path
    notebook:
        "notebooks/get_unused_buses.ipynb"

rule modified_transit_schedule:
    input:
        jar = jar_path,
        lines = "%s/modified_transit_schedules/{schedule}/lines_to_remove.csv" % config_object.output_path,
        schedule = config_object.area_simulation_input_file_path("transit_schedule.xml.gz")
    threads: 1
    resources:
        mem_mb=2048
    output:
        "%s/modified_transit_schedules/{schedule}/transit_schedule.xml.gz" % config_object.output_path
    shell:
        """
        {java_cmd} -Xmx2G -cp {input.jar}  org.eqasim.papers.dourdan_feeder_drt_2024.RemoveTransitLines \
        --schedule-path {input.schedule} --lines-path {input.lines} \
        --output-path {output[0]}
        """

rule modified_transit_schedule_plans:
    input:
        jar = jar_path,
        schedule = "%s/modified_transit_schedules/{schedule}/transit_schedule.xml.gz" % config_object.output_path,
        config = config_object.area_baseline_config_path,
        plans = config_object.area_baseline_simulation_output_file_path("output_plans.xml.gz")
    threads: config_object.area_routing_resources.threads
    resources:
        mem_mb=memory_string_to_mb(config_object.area_routing_resources.memory)
    output:
        "%s/modified_transit_schedules/{schedule}/plans.xml.gz" % config_object.output_path
    shell:
        """
        {java_cmd} -Xmx{config_object.area_routing_resources.memory} -cp {input.jar} \
        org.eqasim.core.scenario.routing.RunPopulationRouting \
        --config-path {input.config} --config:transit.transitScheduleFile {input.schedule} \
        --config:plans.inputPlansFile {input.plans} \
        --config:swissRailRaptor.transferCalculation Initial \
        --modes pt --threads {threads} --output-path {output[0]}
        """

rule drt_stops:
    input:
        jar_path,
        config_object.general_inputs_config.area_path,
        cut_transit_schedule_path,
        cut_network_path
    threads: 1
    resources:
        mem_mb=2048
    output:
        config_object.area_simulation_input_file_path("drt_stops.xml")
    shell:
        """
        {java_cmd} -Xmx2G -cp {input[0]} org.eqasim.papers.dourdan_feeder_drt_2024.TransitScheduleToDrtStops \
        --schedule-path {input[2]} --extent-path {input[1]} --network-path {input[3]} \
        --mode inside_car \
        --output-path {output[0]}
        """

rule deployment_scenario_config:
    input:
        lambda wildcards: [jar_path] + config_object.get_deployment_scenario_configure_inputs(wildcards.deployment_scenario)
    output:
        "%s/%sconfig_{deployment_scenario}.xml" % (config_object.area_simulation_inputs_location, config_object.general_inputs_config.area_prefix)
    threads: 1
    resources:
        mem_mb=2048
    params:
        args=lambda wildcards: config_object.get_deployment_scenario_configure_args(wildcards.deployment_scenario)
    shell:
        """
        {java_cmd} -Xmx2G -cp {input[0]} org.eqasim.papers.dourdan_feeder_drt_2024.ConfigureDrtServices \
        --input-path {input[1]} --output-path {output[0]} \
        --config:multiModeDrt.drt[mode=drt].transitStopFile {input[2]} \
        --config:multiModeDrt.drt[mode=drt].operationalScheme serviceAreaBased \
        --config:multiModeDrt.drt[mode=drt].drtServiceAreaShapeFile {input[3]} \
        --config:eqasim.estimator[mode=drt].estimator DrtUtilityEstimator \
        --config:dvrp.networkModes inside_car \
        {params.args}
        """

rule demand_identification_simulation:
    input:
        unpack(lambda wildcards: config_object.get_simulation_inputs(wildcards.hash, demand_identification=True, jar_path=jar_path))
    output:
        ["%s/simulations/demand_identification/{group}/{hash}/%s" % (config_object.output_path, sim_output) for sim_output in PipelineConfig.RELEVANT_SIMULATION_OUTPUTS],
        "%s/simulations/demand_identification/{group}/{hash}/dvrp_travel_times.csv.gz" % (config_object.output_path)
    threads: config_object.area_simulation_resources.threads
    resources:
        mem_mb=memory_string_to_mb(config_object.area_simulation_resources.memory) + 10240
    params:
        output_dir=lambda wildcards: "%s/simulations/demand_identification/%s/%s" % (config_object.output_path, wildcards.group, wildcards.hash),
        args=lambda wildcards: config_object.get_simulation_args(wildcards.hash, demand_identification=True)
    shell:
        """
        {java_cmd} -XX:MaxRAMPercentage=100.0 -Xmx{config_object.area_simulation_resources.memory} -cp {input.jar_path} \
        org.eqasim.papers.dourdan_feeder_drt_2024.RunSimulation --config-path {input.config} \
        --config:multiModeDrt.drt[mode=drt].vehiclesFile {input.vehicles} \
        --config:plans.inputPlansFile {input.plans} \
        --config:controller.outputDirectory {params.output_dir} \
        --config:eqasim.costParametersPath {input.cost_params} {params.args} \
        --config:transit.transitScheduleFile {input.transit_schedule}
        """


rule fleet_sizing_simulation:
    input:
        unpack(lambda wildcards: config_object.get_simulation_inputs(wildcards.hash, demand_identification=False, fleet_size=wildcards.fleet_size, random_seed=wildcards.seed, jar_path=jar_path))
    output:
        ["%s/simulations/fleet_sizing/{group}/{hash}/{fleet_size}/seeds/{seed}/%s" % (config_object.output_path, sim_output) for sim_output in PipelineConfig.RELEVANT_SIMULATION_OUTPUTS],
    params:
        output_dir = lambda wildcards: "%s/simulations/fleet_sizing/%s/%s/%s/seeds/%s" % (config_object.output_path, wildcards.group, wildcards.hash, wildcards.fleet_size, wildcards.seed),
        args = lambda wildcards: config_object.get_simulation_args(wildcards.hash, demand_identification=False)
    threads: config_object.area_simulation_resources.threads
    resources:
        mem_mb=memory_string_to_mb(config_object.area_simulation_resources.memory) + 10240
    shell:
        """
        {java_cmd} -XX:MaxRAMPercentage=100.0 -Xmx{config_object.area_simulation_resources.memory} -cp {input.jar_path} \
        org.eqasim.papers.dourdan_feeder_drt_2024.RunSimulation --config-path {input.config} \
        --config:multiModeDrt.drt[mode=drt].vehiclesFile {input.vehicles} \
        --config:plans.inputPlansFile {input.plans} \
        --config:controller.outputDirectory {params.output_dir} \
        --config:eqasim.costParametersPath {input.cost_params} {params.args} \
        --config:dvrp.initialTravelTimesFile {input.dvrp_travel_times} \
        --config:transit.transitScheduleFile {input.transit_schedule}
        """


def get_rejection_rate(sim_path):
    import pandas as pd
    df = pd.read_csv("%s/eqasim_drt_passenger_rides.csv" % sim_path, sep=";")
    return df["vehicle_id"].isna().sum() / len(df)

checkpoint fleet_size_evaluation:
    input:
        [["%s/simulations/fleet_sizing/{group}/{hash}/{fleet_size}/seeds/%d/%s" % (config_object.output_path, seed, sim_output) for seed in config_object.fleet_sizing_config.fleet_seeds] for sim_output in PipelineConfig.RELEVANT_SIMULATION_OUTPUTS]
    output:
        ["%s/simulations/fleet_sizing/{group}/{hash}/{fleet_size}/best/%s" % (config_object.output_path, sim_output) for sim_output in PipelineConfig.RELEVANT_SIMULATION_OUTPUTS]
    resources:
        mem_mb=2048
    threads: 1
    run:
        import os
        import shutil
        # Dummy selection of any seed
        selected_dir = os.path.dirname(input[0])
        dest_dir = os.path.dirname(output[0])
        shutil.rmtree(dest_dir, ignore_errors=True)
        shutil.copytree(selected_dir, dest_dir)



def fleet_sizing_input(wildcards):
    left = int(config_object.fleet_sizing_config.fleet_size_precision)
    left_checkpoint = checkpoints.fleet_size_evaluation.get(group=wildcards.group, hash=wildcards.hash, fleet_size=left)
    left_rejection_rate = get_rejection_rate(os.path.dirname(left_checkpoint.output[0]))

    if left_rejection_rate <= float(config_object.fleet_sizing_config.max_rejection_rate):
        return left_checkpoint.output[0]
    right = left * 10
    while True:
        right_checkpoint = checkpoints.fleet_size_evaluation.get(group=wildcards.group, hash=wildcards.hash, fleet_size=right)
        right_value = get_rejection_rate(os.path.dirname(right_checkpoint.output[0]))
        if right_value > flot(config_object.fleet_sizing_config.max_rejection_rate):
            left = right
            right *= 2
        else:
            break
    while right - left > int(config_object.fleet_sizing_config.fleet_sizing_precision):
        middle = int( (right + left) / 2)
        middle_checkpoint = checkpoints.fleet_size_evaluation.get(group=wildcards.group, hash=wildcards.hash, fleet_size=middle)
        middle_value = get_rejection_rate(os.path.dirname(middle_checkpoint.output[0]))
        if middle_value > float(config_object.fleet_sizing_config.max_rejection_rate):
            right = middle
            right_checkpoint = middle_checkpoint
        else:
            left = middle
    return right_checkpoint.output[0]


rule fleet_sizing:
    input:
        fleet_sizing_input
    threads: 1
    resources:
        mem_mb=2048
    output:
        ["%s/simulations/evaluation/{group}/{hash}/%s" % (config_object.output_path, sim_output) for sim_output in PipelineConfig.RELEVANT_SIMULATION_OUTPUTS],
    run:
        import shutil
        import os
        source_dir_path = os.path.dirname(input[0])
        dest_dir_path = os.path.dirname(output[0])
        shutil.rmtree(dest_dir_path, ignore_errors=True)
        shutil.copytree(source_dir_path, dest_dir_path)

rule evaluation_simulation:
    input:
        unpack(lambda wildcards: config_object.get_simulation_inputs(wildcards.hash, demand_identification=False, jar_path=jar_path))
    output:
        ["%s/simulations/evaluation/{group}/{hash}/%s" % (config_object.output_path, sim_output) for sim_output in PipelineConfig.RELEVANT_SIMULATION_OUTPUTS]
    params:
        output_dir=lambda wildcards: "%s/simulations/evaluation/%s/%s" % (config_object.output_path, wildcards.group, wildcards.hash),
        args=lambda wildcards: config_object.get_simulation_args(wildcards.hash, demand_identification=False)
    threads: config_object.area_simulation_resources.threads
    resources:
        mem_mb=memory_string_to_mb(config_object.area_simulation_resources.memory) + 10240
    shell:
        """
        {java_cmd} -XX:MaxRAMPercentage=100.0 -Xmx{config_object.area_simulation_resources.memory} -cp {input.jar_path} \
        org.eqasim.papers.dourdan_feeder_drt_2024.RunSimulation --config-path {input.config} \
        --config:multiModeDrt.drt[mode=drt].vehiclesFile {input.vehicles} \
        --config:plans.inputPlansFile {input.plans} \
        --config:controller.outputDirectory {params.output_dir} \
        --config:eqasim.costParametersPath {input.cost_params} {params.args} \
        --config:dvrp.initialTravelTimesFile {input.dvrp_travel_times} \
        --config:transit.transitScheduleFile {input.transit_schedule}
        """



rule simulation_summary:
    input:
        lambda wildcards: ["%s/simulations/evaluation/%s/%s/%s" % (config_object.output_path, wildcards.group, wildcards.hash, sim_output) for sim_output in PipelineConfig.RELEVANT_SIMULATION_OUTPUTS]
    output:
        "%s/simulations/evaluation/{group}/{hash}/summary.yaml" % config_object.output_path
    params:
        summary=lambda wildcards: config_object.hash_to_config(wildcards.hash).get_dict()
    threads: 1
    resources:
        mem_mb=1024
    run:
        import yaml
        with open(output[0], "w") as f:
            yaml.dump(params.summary,  f, default_flow_style=False)


rule all:
    default_target: True
    input:
        baseline_trips_path,
        config_object.area_baseline_simulation_output_file_path("eqasim_trips.csv"),
        [config_object.get_modified_transit_schedule_path(modified_transit_schedule) for modified_transit_schedule in config_object.modified_transit_schedules.values()],
        [config_object.get_deployment_scenario_config_path(deployment_scenario) for deployment_scenario in config_object.deployment_scenarios.values()],
        ["%s/simulations/evaluation/%s/%s/output_plans.xml.gz" % (config_object.output_path, simulation_config.deployment_scenario.name, simulation_config.hash_code) for simulation_config in config_object.simulation_configs.values()],
        ["%s/simulations/evaluation/%s/%s/summary.yaml" % (config_object.output_path, simulation_config.deployment_scenario.name, simulation_config.hash_code) for simulation_config in config_object.simulation_configs.values()]