import os
import glob
import collections.abc
import pickle
import json
import sys
import importlib.util

spec = importlib.util.spec_from_file_location("lib", "lib/__init__.py")
module_obj = importlib.util.module_from_spec(spec)
sys.modules["lib"] = module_obj
spec.loader.exec_module(module_obj)

from lib import PipelineConfig
from lib import to_absolute

def recursive_update(destination, source):
    for k, v in source.items():
        if k not in destination:
            destination[k] = v
        elif isinstance(v, collections.abc.Mapping):
            destination[k] = recursive_update(destination.get(k, {}), v)
    return destination

def repo_url_to_id(repo_url):
    # SSH link example "git@github.com:eqasim-org/ile-de-france.git"
    # HTTPS link example https://github.com/eqasim-org/ile-de-france.git
    assert isinstance(repo_url,str)
    if not repo_url.startswith("git@github.com") and not repo_url.startswith("https://github.com"):
        raise Exception("Invalid repo_url")
    components = repo_url.split("/")
    repo_owner, repo_name = components[-2], components[-1]
    repo_name = repo_name.replace(".git","")
    repo_owner = repo_owner.split(":")[-1]
    return "%s/%s" % (repo_owner, repo_name)


default_config = {"java": {"java_cmd": "java", "mvn_cmd": "mvn"},
                  "resources": {"max-threads": 12, "memory": "50G"},
                  "output_path": to_absolute("outputs", workflow.basedir)}

recursive_update(config, default_config)
config_object = PipelineConfig(config, workflow.basedir, workflow.cores)


# Maven and Java related variables
mvn_project_base_path = to_absolute("../../../../../", workflow.basedir)

pom_path = os.path.join(mvn_project_base_path, "pom.xml")
mvn_repository_path = to_absolute(".m2", workflow.basedir)

java_sources_base_path = to_absolute("../../java", workflow.basedir)

java_sources_paths = [to_absolute(f, workflow.basedir) for f in
                      glob.iglob(java_sources_base_path + "**/**",recursive=True) if os.path.isfile(f)]

jar_path = to_absolute(os.path.join("../../../../","target","gpe_2025-1.0-SNAPSHOT.jar"), workflow.basedir)


mvn_cmd = config["java"]["mvn_cmd"]
java_cmd = config["java"]["java_cmd"]


memory_str = config["resources"]["memory"]

def memory_string_to_mb(memory_string):
    assert isinstance(memory_string, str)
    nb = int(memory_string[0:len(memory_string)-1])
    if memory_str.endswith("G"):
        nb *= 1024
    elif memory_str.endswith("M"):
        raise Exception("Bad memory format")
    return nb

memory_mb = memory_string_to_mb(config_object.resources.memory)
analysis_memory_mb = memory_string_to_mb(config_object.resources.analysis_memory)

java_memory_offset = 10240

def get_simulation_input_file(input_file, scenario, **kwargs):
    return os.path.join(config_object.output_path, "cache/inputs/%s" % scenario, config_object.scenarios[scenario].prefix + input_file)


wildcard_constraints:
    scenario="[a-zA-Z]+",
    mode="[a-zA-Z]+",
    remaining="(_.+){0,1}"


# We need to create the input copying rules in a procedural way because we need the scenario prefix in the output path
for scenario in config_object.scenarios.values():
    contents = list(os.listdir(scenario.path))
    if len(contents) == 0:
        raise Exception("Folder indicated for scenario %s is empty" % scenario.scenario_name)
    rule:
        name:
            f"copy_{scenario.scenario_name}_inputs"
        input:
            ["%s/%s" % (scenario.path, c) for c in contents]
        output:
            ["%s/cache/inputs/%s/%s" % (config_object.output_path, scenario.scenario_name, c) for c in contents]
        params:
            inputs_location = scenario.path,
            outputs_location = lambda wildcards, output: os.path.dirname(output[0])
        threads: 1
        resources:
            mem_mb=1024
        shell:
            '''
            pwd
            echo "Creating folder {params.outputs_location}"
            mkdir -p {params.outputs_location}
            echo "Copying files into {params.outputs_location}"
            cp {params.inputs_location}/* {params.outputs_location}/
            '''

# This rule compiles the current maven module into a standalone jar

rule compile:
    input:
        java_sources_paths,
        pom_path
    output:
        jar_path
    params:
        mvn_cmd=config_object.java.mvn_cmd
    threads: min(config_object.resources.max_threads, 4)
    resources:
        mem_mb=4096
    shell:
        '{params.mvn_cmd} package -Pstandalone --also-make --file "{pom_path}" -Dmaven.repo.local="{mvn_repository_path}" -DskipTests'


# The following rules are related to the evaluation of quality of PT trips between the control and the GPE scenarios
# First, this rule processes the population so that each agent has only one trip and all trips are set to a certain mode
rule one_agent_per_trip:
    input:
        jar=jar_path,
        population=lambda wildcards: get_simulation_input_file("population.xml.gz", wildcards.scenario),
    output:
        "%s/routing/inputs/split_population_{scenario}_{mode}.xml.gz" % config_object.output_path
    threads: 1
    resources:
        mem_mb=memory_string_to_mb(config_object.resources.population_splitting_memory)+ java_memory_offset
    params:
        java_cmd=config_object.java.java_cmd,
        memory_str=config_object.resources.population_splitting_memory
    shell:
        '''
        mkdir -p "$(dirname {output[0]})"
        {params.java_cmd} -Xmx{params.memory_str} -cp {input.jar} org.eqasim.papers.gpe2025.utils.OneAgentPerTrip \
        --input-path={input.population} --override-mode={wildcards.mode} --output-path={output[0]}
        '''

# The rule below performs the population routing.
# The base version of this rule takes the initial configuration of the scenario as well as the split plans
rule run_population_routing:
    input:
        jar=jar_path,
        config=lambda wildcards: get_simulation_input_file("config.xml", wildcards.scenario),
        plans="%s/routing/inputs/split_population_{scenario}_{mode}.xml.gz" % config_object.output_path
    output:
        "%s/routing/outputs/split_population_{scenario}_{mode}.xml.gz" % config_object.output_path
    params:
        memory_str=config_object.resources.memory,
        java_cmd=config_object.java.java_cmd,
        extra_args=""
    threads: config_object.resources.max_threads
    resources:
        mem_mb=memory_mb + java_memory_offset
    shell:
        '''
        mkdir -p "$(dirname {output[0]})"
        {params.java_cmd} -Xmx{params.memory_str} -XX:MaxRAMPercentage=100.0 -cp {input.jar} org.eqasim.core.scenario.routing.RunPopulationRouting \
        --config-path={input.config} --output-path={output[0]} --config:plans.inputPlansFile={input.plans} \
        --threads={threads} {params.extra_args}
        '''

# The following rule is an override of the previous one focusing on routing trips in a specific feeder setting
use rule run_population_routing as run_population_routing_with_feeders with:
    input:
        jar=jar_path,
        config="%s/cache/inputs/{scenario}/config_abstract_access_{radius}_{frequency}_{speed_index}.xml" % config_object.output_path,
        plans="%s/routing/inputs/split_population_{scenario}_{mode}.xml.gz" % config_object.output_path
    output:
        "%s/routing/outputs/split_population_{scenario}_{mode}_{radius}_{frequency}_{speed_index}.xml.gz" % config_object.output_path

# This rule is a generic one that allows to perform simulations
rule simulation:
    input:
        jar=jar_path,
        config=""
    params:
        extra_args = "",
        memory_str=config_object.resources.memory,
        java_cmd=config_object.java.java_cmd
    threads: min(config_object.resources.max_threads, 12)
    resources:
        mem_mb=memory_mb + java_memory_offset
    output:
        output_path=""
    shell:
        '''
        {params.java_cmd} -Xmx{params.memory_str} -XX:MaxRAMPercentage=100.0 -cp {input.jar} org.eqasim.papers.gpe2025.RunSimulation \
        --config-path={input.config} --config:controller.outputDirectory={output.output_path} \
        --config:global.numberOfThreads={threads} {params.extra_args}
        '''

# This rule performs simulations of split populations that were previously routed
use rule simulation as post_routing_simulation with:
    input:
        jar=jar_path,
        config=lambda wildcards: get_simulation_input_file("config.xml", wildcards.scenario),
        plans="%s/routing/outputs/split_population_{scenario}_{mode}.xml.gz" % config_object.output_path
    params:
        extra_args = lambda wildcards, input: "--config:controller.lastIteration=0 --config:swissRailRaptor.transferCalculation=Adaptive --config:plans.inputPlansFile=%s" % input.plans,
    output:
        output_path=directory("%s/routing/outputs/simulated_{scenario}_{mode}" % config_object.output_path)


# This rule does the same thing as the one above but for feeder scenarios
use rule post_routing_simulation as post_routing_simulation_with_feeders with:
    input:
        jar=jar_path,
        config="%s/cache/inputs/{scenario}/config_abstract_access_{radius}_{frequency}_{speed_index}.xml" % config_object.output_path,
        plans="%s/routing/outputs/split_population_{scenario}_{mode}_{radius}_{frequency}_{speed_index}.xml.gz" % config_object.output_path
    output:
        output_path=directory("%s/routing/outputs/simulated_{scenario}_{mode}_{radius}_{frequency}_{speed_index}" % config_object.output_path)

# This rule provides the generic functionality of running the standalone mode choice
rule mode_choice:
    input:
        jar=jar_path,
        config=""
    params:
        extra_args="",
        memory_str=config_object.resources.memory,
        java_cmd=java_cmd
    threads:
        config_object.resources.max_threads
    resources:
        mem_mb=memory_mb + java_memory_offset
    output:
        output_path=""
    shell:
        '''
        {params.java_cmd} -Xmx{params.memory_str} -XX:MaxRAMPercentage=100.0 -cp {input.jar} org.eqasim.core.standalone_mode_choice.RunStandaloneModeChoice \
        --config-path={input.config} --config:standaloneModeChoice.outputDirectory={output.output_path} \
        --config:standaloneModeChoice.removePersonsWithNoValidAlternatives=true --config:global.numberOfThreads={threads} {params.extra_args}
        '''

# Runs the standalone mode choice for a scenario without feeder services
use rule mode_choice as regular_mode_choice with:
    input:
        jar=jar_path,
        config=lambda wildcards: get_simulation_input_file("config.xml", wildcards.scenario)
    output:
        output_path=directory("%s/mode_choice/outputs/{scenario}" % config_object.output_path)

# Runs the standalone mode choice for a scenario with feeder services
use rule mode_choice as feeder_mode_choice with:
    input:
        jar=jar_path,
        config="%s/cache/inputs/{scenario}/config_abstract_access_{radius}_{frequency}_{speed_index}.xml" % config_object.output_path
    output:
        output_path=directory("%s/mode_choice/outputs/{scenario}_{radius}_{frequency}_{speed_index}" % config_object.output_path)

# Performs the simulation following a standalone mode choice run of a scenario (with or without feeders)
use rule simulation as post_mode_choice_simulation with:
    input:
        jar=jar_path,
        config=lambda wildcards: get_simulation_input_file("config.xml", wildcards.scenario),
        mode_choice_outputs="%s/mode_choice/outputs/{scenario}{remaining}" % config_object.output_path
    output:
        output_path=directory("%s/mode_choice/outputs_simulated/{scenario}{remaining}" % config_object.output_path)
    params:
        extra_args = lambda wildcards, input: "--config:controller.lastIteration=0 --config:swissRailRaptor.transferCalculation=Adaptive --config:plans.inputPlansFile=%s/output_plans.xml.gz" % input.mode_choice_outputs

# Creates abstract accesses items files
rule create_abstract_accesses:
    params:
        radius=lambda wildcards: wildcards.radius,
        speed=lambda wildcards: config_object.scenarios[wildcards.scenario].feeders.speeds[int(wildcards.speed_index)],
        using_routed_distance=False,
        access_type="bus",
        frequency=lambda wildcards: wildcards.frequency
    resources:
        mem_mb=512
    output:
        "%s/abstract_accesses/items/{scenario}/{radius}_{frequency}_{speed_index}.xml" % config_object.output_path
    threads: 1
    script:
        "../scripts/create_abstract_accesses.py"

# Create config files
rule adapt_config:
    input:
        config=lambda wildcards: get_simulation_input_file("config.xml", wildcards.scenario),
        abstract_access_items="%s/abstract_accesses/items/{scenario}/{radius}_{frequency}_{speed_index}.xml" % config_object.output_path,
        jar=jar_path
    output:
        "%s/cache/inputs/{scenario}/config_abstract_access_{radius}_{frequency}_{speed_index}.xml" % config_object.output_path
    params:
        java_cmd=java_cmd,
        memory_str=memory_str
    threads: 1
    resources:
        mem_mb=memory_mb + java_memory_offset
    shell:
        '''
        {params.java_cmd} -Xmx{params.memory_str} -cp {input.jar} org.eqasim.core.simulation.modes.transit_with_abstract_access.utils.AdaptConfigForTransitWithAbstractAccess \
        --accesses-file-path={input.abstract_access_items} \
        --mode-name=transitWithAbstractAccess --input-config-path={input.config} --output-config-path={output[0]}
        '''



def get_non_feeder_related_outputs(output_type, scenarios=None):
    if scenarios is None:
        scenarios  = [s for s in  config_object.scenarios.values() if s.feeders is None]
    else:
        if not isinstance(scenarios, list):
            scenarios = [scenarios]
        for s in scenarios:
            if s.feeders is not None:
                raise Exception("Scenario %s has feeder services configured" % s.scenario_name)
    if output_type == "mode_choice":
        l = ["%s/mode_choice/outputs_simulated/%s" % (config_object.output_path, s.scenario_name) for s in scenarios]
    elif output_type == "routing":
        l = ["%s/routing/outputs/simulated_%s_pt" % (config_object.output_path, s.scenario_name) for s in scenarios]
    elif output_type == "simulation":
        l = ["%s/simulations/outputs/%s" % (config_object.output_path, s.scenario_name) for s in scenarios]
    else:
        raise Exception("Unsupported output type %s" % output_type)
    return l


'''
The method below retrieves the routing or mode choice outputs for one or more feeder scenarios
@:param output_type: either 'routing' or 'mode_choice' depending on the output desired
@:param scenarios: The scenarios for which the outputs are desired. If None, will retrieve the outputs of all feeder scenarios
@:param radiis: if not None, specifies a set of radius values for which the outputs are desired (has to be a subset of the values specified in the scenario)
@:param frequencies: if not None, specifies a set of frequency values for which the outputs are desired (has to be a subset of the values specified in the scenario)
@:param speeds: if not None, specifies a set of speed values for which the outputs are desired (has to be a subset of the values specified in the scenario)
'''
def get_feeder_related_outputs(output_type, scenarios=None, radiis=None, frequencies=None, speeds=None):
    if scenarios is None:
        scenarios = [s for s in  config_object.scenarios.values() if s.feeders is not None]
    else :
        if not isinstance(scenarios, list):
            scenarios = [scenarios]
        for s in scenarios:
            if s.feeders is None:
                raise Exception("Scenario %s has no feeder services configured" % s.scenario_name)

    if radiis is not None and not isinstance(radiis, list):
        radiis = [radiis]
    if frequencies is not None and not isinstance(frequencies, list):
        frequencies = [frequencies]
    if speeds is not None and not isinstance(speeds, list):
        speeds = [speeds]
    if output_type == "routing":
        base_path = "%s/routing/outputs/simulated_%s_transitWithAbstractAccess_{radius}_{frequency}_{speed_index}"
    elif output_type == "mode_choice":
        base_path = "%s/mode_choice/outputs_simulated/%s_{radius}_{frequency}_{speed_index}"
    elif output_type == "simulation":
        base_path = "%s/simulations/outputs/%s_{radius}_{frequency}_{speed_index}"
    else:
        raise Exception("Unkown output_type %s" % output_type)

    l = [expand(base_path % (config_object.output_path, s.scenario_name),
        radius=[radius for radius in s.feeders.radiis if radius in (radiis if radiis is not None else s.feeders.radiis)],
        frequency=[frequency for frequency in s.feeders.frequencies if frequency in (frequencies if frequencies is not None else s.feeders.frequencies)],
        speed_index=[i for i in range(len(s.feeders.speeds)) if s.feeders.speeds[i] in (speeds if speeds is not None else s.feeders.speeds)])  for s in scenarios]

    l = flatten(l)
    if len(l) == 1:
        l = l[0]
    return l


# This rule performs the sensitivity analysis for feeder services on a single scenario based on routing results
rule routing_feeder_analysis:
    input:
        feeder_outputs=lambda wildcards: get_feeder_related_outputs("routing", config_object.scenarios[wildcards.scenario]),
        no_feeder_outputs= lambda wildcards: get_non_feeder_related_outputs("routing", config_object.scenarios[config_object.scenarios[wildcards.scenario].feeders.no_feeder_counterpart]) if config_object.scenarios[wildcards.scenario].feeders.no_feeder_counterpart is not None else []
    params:
        config = config,
        pipeline_kwargs = dict(basedir=workflow.basedir, max_cores=workflow.cores),
        # Multiple Named input parameters that are lists get converted into one list losing the names
        # So I have to put them again as parameters here
        feeder_outputs = lambda wildcards: get_feeder_related_outputs("routing", config_object.scenarios[wildcards.scenario]),
        no_feeder_outputs = lambda wildcards: get_non_feeder_related_outputs("routing", config_object.scenarios[config_object.scenarios[wildcards.scenario].feeders.no_feeder_counterpart]) if config_object.scenarios[wildcards.scenario].feeders.no_feeder_counterpart is not None else []
    output:
        "%s/routing/feeder_analyses/{scenario}.ipynb" % config_object.output_path
    threads: 1
    resources:
        mem_mb=analysis_memory_mb
    log:
        notebook="%s/routing/feeder_analyses/{scenario}.ipynb" % config_object.output_path
    notebook:
        "../notebooks/routing_feeder_analysis.ipynb"

# This rule performs the sensitivity analysis for feeder services on a single scenario based on mode choice results
rule mode_choice_feeder_analysis:
    input:
        feeder_outputs=lambda wildcards: get_feeder_related_outputs("mode_choice", [config_object.scenarios[wildcards.scenario]]),
        no_feeder_outputs=lambda wildcards: get_non_feeder_related_outputs("mode_choice", config_object.scenarios[config_object.scenarios[wildcards.scenario].feeders.no_feeder_counterpart]) if config_object.scenarios[wildcards.scenario].feeders.no_feeder_counterpart is not None else []
    output:
        "%s/mode_choice/feeder_analyses/{scenario}.ipynb" % config_object.output_path
    threads: 1
    resources:
        mem_mb=analysis_memory_mb
    shell: # Just a mock for now before we initialize the notebook
        '''
        touch {output[0]}
        '''

# Regular simulation related rules
use rule run_population_routing as full_pt_rerouting with:
    input:
        jar = jar_path,
        config = lambda wildcards: get_simulation_input_file("config.xml", wildcards.scenario),
        plans = lambda wildcards: get_simulation_input_file("population.xml.gz", wildcards.scenario)
    params:
        extra_args = "--modes=pt"
    output:
        "%s/simulations/prerouting/{scenario}.xml.gz" % config_object.output_path


# This rule is a generic one that allows to perform simulations
use rule simulation as regular_simulation with:
    input:
        jar=jar_path,
        config=lambda wildcards: get_simulation_input_file("config.xml", wildcards.scenario),
        plans="%s/simulations/prerouting/{scenario}.xml.gz" % config_object.output_path
    params:
        extra_args = lambda wildcards: "--config:plans.inputPlansFile=%s/simulations/prerouting/%s.xml.gz" % (config_object.output_path, wildcards.scenario),
        memory_str=config_object.resources.memory,
        java_cmd=config_object.java.java_cmd
    output:
        output_path="%s/simulations/outputs/{scenario}" % config_object.output_path

# Runs the standalone mode choice for a scenario with feeder services
use rule simulation as regular_feeder_simulation with:
    input:
        jar=jar_path,
        config="%s/cache/inputs/{scenario}/config_abstract_access_{radius}_{frequency}_{speed_index}.xml" % config_object.output_path,
        plans="%s/simulations/prerouting/{scenario}.xml.gz" % config_object.output_path
    params:
        extra_args = lambda wildcards: "--config:plans.inputPlansFile=%s/simulations/prerouting/%s.xml.gz" % (config_object.output_path, wildcards.scenario),
        memory_str=config_object.resources.memory,
        java_cmd=config_object.java.java_cmd
    output:
        output_path=directory("%s/simulations/outputs/{scenario}_{radius}_{frequency}_{speed_index}" % config_object.output_path)

# This method is in charge of retrieving the inputs required for running analyses
# These inputs are the outputs of running a routing or a mode choice
def get_analysis_inputs(analysis):
    outputs = {label: ("%s/routing/outputs/simulated_%s_pt" if analysis.type == "routing" else "%s/mode_choice/outputs_simulated/%s") % (config_object.output_path, item[0].scenario_name) for label, item in analysis.scenario_items.items() if item[2] is None}
    outputs.update({label: get_feeder_related_outputs(analysis.type, scenarios=item[0], radiis=item[2]["radius"], frequencies=item[2]["frequency"], speeds=item[2]["speed"]) for label, item in analysis.scenario_items.items() if item[2] is not None})
    return outputs

# Here we programmatically create the rules in charge of performing the analyses specified in the config file
# These analyses simply compare between multiple scenario outputs (either from routing or mode choice)
for analysis in config_object.analyses.values():
    rule:
        name: "analysis_%s" % analysis.analysis_name
        input:
            **get_analysis_inputs(analysis) # For some reason snakemake converts this into a list so I have to also pass it as a parameter to have the labels too
        params:
            config = config,
            pipeline_kwargs = dict(basedir=workflow.basedir, max_cores=workflow.cores),
            analysis_name = analysis.analysis_name,
            scenarios = dict(**get_analysis_inputs(analysis)),
            reference = analysis.reference
        threads: 1
        resources:
            mem_mb=analysis_memory_mb
        output:
            "%s/%s/scenario_comparisons/%s.ipynb" % (config_object.output_path, analysis.type, analysis.analysis_name)
        log:
            notebook="%s/%s/scenario_comparisons/%s.ipynb" % (config_object.output_path, analysis.type, analysis.analysis_name)
        notebook: "../notebooks/%s_scenario_analysis.ipynb" % analysis.type


def get_all_outputs():
    outputs = set()

    # We check if all non feeder scenarios are to be considered
    if config_object.run_non_feeders != "requiredOnly":
        if config_object.run_non_feeders != "all":
            methods = [config_object.run_non_feeders]
        else:
            methods = ["mode_choice", "routing"]
        for method in methods:
            outputs = outputs.union(get_non_feeder_related_outputs(method))

    # Next we check feeder scenarios
    if config_object.run_feeders != "requiredOnly":
        scenarios = [s for s in config_object.scenarios.values() if s.feeders is not None]
        if config_object.run_feeders in ["all", "mode_choice"]:
            outputs = outputs.union(["%s/mode_choice/feeder_analyses/%s.ipynb" % (config_object.output_path, s.scenario_name) for s in scenarios])
        if config_object.run_feeders in ["all", "routing"]:
            outputs = outputs.union(["%s/routing/feeder_analyses/%s.ipynb" % (config_object.output_path, s.scenario_name) for s in scenarios])

    # outputs = outputs.union(get_non_feeder_related_outputs("simulation"))
    # outputs = outputs.union(get_feeder_related_outputs("simulation"))

    # Now we check the analyses
    for analysis in config_object.analyses.values():
        outputs.add("%s/%s/scenario_comparisons/%s.ipynb" % (config_object.output_path, analysis.type, analysis.analysis_name))

    return outputs

rule all:
    default_target: True
    input:
        get_all_outputs()